version: '3'
services:
  db:
    build: ./db/
    ports:
    - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: happy-jpa
