spring:
  datasource:
    url: "jdbc:mysql://localhost:13306/dev?useUnicode=true&amp;characterEncoding=utf-8"
    username: "dev"
    password: "dev"
    driver-class-name : "com.mysql.jdbc.Driver"
    max-idle: 10
    min-idle: 5
    initial-size: 5
    max-wait: 10000